server:
  port: 8081
spring:
   application:
      name: spring boot 
   
   boot:
      admin:
         ui:
            title: "Projeto de monitoramento das apis"

logging:
   level:
      root: INFO

management:
   endpoints:
      web:
         exposure:
            include: "*"
   endpoint:
      health:
         show-details: always
        # Eureka Configuration
         eureka:
           instance:
             leaseRenewalIntervalInSeconds: 10
             leaseExpirationDurationInSeconds: 30
           client:
             registerWithEureka: true
             serviceUrl:
               defaultZone: http://localhost:8750/eureka
             healthcheck:
               enabled: true